# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

#before_script:
#    - npm install
#    - npm run deploy

#stage_deploy:
#    artifacts:
#        paths:
#          - build/
#    only:
#        - dev
#    script:
#        - ssh-add <(echo "$STAGING_PRIVATE_KEY")
#        - ssh -p22 server_user@server_host "mkdir htdocs/wp-content/themes/_tmp"
#        - scp -P22 -r build/* server_user@server_host:htdocs/wp-content/themes/_tmp
#        - ssh -p22 server_user@server_host "mv htdocs/wp-content/themes/live htdocs/wp-content/themes/_old && mv htdocs/wp-content/themes/_tmp htdocs/wp-content/themes/live"
#        - ssh -p22 server_user@server_host "rm -rf htdocs/wp-content/themes/_old"


test:
  stage: test
  script:
    - npm install
    - npm test

pack:
  stage: deploy
  script:
    - npm install
    - npm pack
  artifacts:
    paths:
    - ./*.tgz

production:
    type: deploy
    script:
        - npm install
        - npm start
        - gem install dpl
        - dpl --provider=heroku --app=ecc-test --api-key=8cdde59c-f589-4aca-b5ab-f98dcc733476
    only:
        - master
